Repository LiskHQ/lisk-explorer, pull requests merged in 2018-05, with the labels that each got.

#608 Add additional data to transaction page - Closes #577
  src/components/transactions/transactions.html
Labels: :eye: pending review

#593 Improve readability and update the Bittrex logo - Closes #590
  src/assets/img/exchanges/bittrex.png
  src/assets/styles/common.css
  src/components/bread-crumb/bread-crumb.css
  src/components/header/header.css
  src/components/transactions/transactions.html
Labels: :eye: pending review

#605 Tooltip should not trigger on click - Closes #604
  src/assets/styles/common.css
Labels: :eye: pending review

#582 Use core epoch - Closes #534
  api/index.js
  app.js
  lib/api/common.js
  src/app/run.js
  src/filters/epoch-stamp.js
Labels: :white_check_mark: ready

#589 Add new coincheck wallet to known.json - Closes #588
  known.json
Labels: :building_construction: in progress

#609 Update Jenkinsfile to implement slack notifications
  Jenkinsfile
Labels: :white_check_mark: ready

#614 Update e2e tests - Closes #506
  features/address.feature
  features/block.feature
  features/delegate.feature
  features/delegateMonitor.feature
  features/footer.feature
  features/menu.feature
  features/networkMonitor.feature
  features/step_definitions/generic.step.js
  features/topAccounts.feature
  features/transaction.feature
  src/components/header/header.html
  src/components/top-accounts/top-accounts.html
  src/components/transactions/transactions.html
Labels: :eye: pending review

#620 Changed networkHeight to height - Solves #619
  lib/api/blocks.js
Labels: :white_check_mark: ready

#587 Add API documentation - Closes #584
  API_ENDPOINTS.md
Labels: :white_check_mark: ready

#592 Bad performance - Closes #474
  lib/api/transactions.js
  src/filters/tx-recipient.js
  src/filters/tx-sender.js
  test/api/transactions.js
  utils/knownAddresses.js
Labels: :white_check_mark: ready

#603 Improve all transactions tab - Closes #591
  Jenkinsfile
  features/menu.feature
  lib/api/transactions.js
  src/services/address-txs.js
  src/services/less-more-by-timestamp.js
  src/services/less-more.js
Labels: :eye: pending review

#618 Remove cruft from Dockerfile - Closes #617
  Dockerfile
Labels: :white_check_mark: ready

#621 Delegate proposal - Closes #573
  api/delegates.js
  config.global.js
  config.js
  lib/api/delegates.js
  sockets/header.js
  src/assets/styles/common.css
  src/components/address/address.html
  src/components/delegate-monitor/delegate-monitor.component.js
  src/components/delegate-monitor/delegate-monitor.html
  src/components/delegate-monitor/delegate-monitor.service.js
  src/components/delegate/delegate.html
  src/components/header/header.directive.js
  src/components/header/header.service.js
  src/filters/index.js
  src/filters/proposal.js
  test/api/delegates.js
  test/config.test
Labels: :white_check_mark: ready

#624 Jenkins Slack notifications for 1.6.1 - Closes #573
  Jenkinsfile
Labels: :white_check_mark: ready

#622 Redis cache error - Closes #598
  app.js
Labels: :white_check_mark: ready

#613 Fix column order on transaction table - Closes #612
  features/address.feature
  features/block.feature
  features/transaction.feature
  src/components/transactions/transactions.html
  src/shared/transaction-item/transaction-item.html
  src/shared/transactions-list/transactions-list.html
Labels: :white_check_mark: ready

#633 Transactions table update - Closes #632
  src/shared/transaction-item/transaction-item.html
  src/shared/transactions-list/transactions-list.html
Labels: :white_check_mark: ready

#634 Fix for broken sort order display in trasaction view - Closes #599
  features/address.feature
  features/block.feature
  src/assets/styles/common.css
  src/services/order-by.js
  src/shared/transaction-item/transaction-item.html
  src/shared/transactions-list/transactions-list.directive.js
  src/shared/transactions-list/transactions-list.html
Labels: :white_check_mark: ready

#655 Breadcrumb style update - Closes #641
  src/components/bread-crumb/bread-crumb.css
Labels: :white_check_mark: ready

#654 Remove opacity network bar - Closes #637
  src/components/header/header.css
Labels: :white_check_mark: ready

#658 Matching Address and Final Balance styling - Closes #647
  src/assets/styles/common.css
  src/components/address/address.html
Labels: :eye: pending review

#659 Block ID displayed in header only - Closes #656
  src/components/blocks/block.html
Labels: :white_check_mark: ready

#661 Transaction details - Closes #657
  features/transaction.feature
  src/components/transactions/transactions.html
Labels: :white_check_mark: ready

#660 Transaction view update - Closes #642
  features/transaction.feature
  src/assets/styles/common.css
  src/components/transactions/transactions.html
Labels: :white_check_mark: ready

#664 Make labels bold on network status bar - Closes #638
  src/components/header/header.html
Labels: :eye: pending review

#663 Always close currency dropdown after selecting - Closes #649
  src/components/currency-selector/currency-selector.directive.js
Labels: :white_check_mark: ready

#665 Reduce space between lines on mobile view of transactions table - Closes #643
  src/assets/styles/tableMobile.css
Labels: :white_check_mark: ready

#667 Apply new button style - Closes #644
  src/assets/styles/common.css
  src/components/blocks/blocks.html
Labels: :white_check_mark: ready

#666 Show search input when not on mobile - Closes #596
  features/menu.feature
  src/components/header/header.css
  src/components/header/header.html
  src/components/search/search.directive.js
  src/components/search/search.html
Labels: :white_check_mark: ready

#676 Add current page to the breadcrumb bar - Closes #640
  features/address.feature
  features/block.feature
  features/delegate.feature
  features/transaction.feature
  src/app/states.js
  src/components/bread-crumb/bread-crumb.directive.js
Labels: :white_check_mark: ready

#677 Update decimal places options - Closes #648
  features/footer.feature
  src/components/footer/footer.html
Labels: :white_check_mark: ready

#675 Change tooltip position avoiding undesired margins - Closes #670
  src/assets/styles/common.css
  src/components/address/address.html
  src/directives/clip-copy.js
  src/shared/transaction-item/transaction-item.html
Labels: :eye: pending review

#679 Automatically focus on searchbox after expanding - Closes #669
  src/components/header/header.css
  src/components/search/search.directive.js
  src/components/search/search.html
Labels: :eye: pending review

#680 Add changes from 1.6.1 - Closes #508
  src/assets/styles/common.css
  src/components/address/address.html
  src/components/header/header.css
  src/components/search/search.directive.js
  src/components/search/search.html
  src/directives/clip-copy.js
  src/shared/transaction-item/transaction-item.html
Labels: :building_construction: in progress

#682 Angular version lock - Closes #681
  .babelrc
  package.json
  webpack.config.js
Labels: :building_construction: in progress, :white_check_mark: ready
