Repository LiskHQ/lisk-explorer, pull requests merged in 2018-04, with the labels that each got.

#481 Update the UI to align with new Lisk design - Closes #442
  src/assets/fonts/gilroy/gilroy-bold.eot
  src/assets/fonts/gilroy/gilroy-bold.ttf
  src/assets/fonts/gilroy/gilroy-bold.woff
  src/assets/fonts/gilroy/gilroy-bold.woff2
  src/assets/fonts/gilroy/gilroy-extra-bold.eot
  src/assets/fonts/gilroy/gilroy-extra-bold.ttf
  src/assets/fonts/gilroy/gilroy-extra-bold.woff
  src/assets/fonts/gilroy/gilroy-extra-bold.woff2
  src/assets/fonts/roboto/Roboto-Bold.ttf
  src/assets/fonts/roboto/Roboto-BoldItalic.ttf
  src/assets/fonts/roboto/Roboto-Regular.ttf
  src/assets/img/lisk-logo.svg
  src/assets/styles/common.css
  src/components/activity-graph/activity-graph.css
  src/components/activity-graph/activity-graph.html
  src/components/activity-graph/activity-graph.service.js
  src/components/address/address.html
  src/components/blocks/block.html
  src/components/blocks/blocks.html
  src/components/bread-crumb/bread-crumb.css
  src/components/delegate-monitor/delegate-monitor.css
  src/components/delegate-monitor/delegate-monitor.html
  src/components/delegate/delegate.html
  src/components/footer/footer.html
  src/components/header/header.css
  src/components/header/header.html
  src/components/home/home.html
  src/components/market-watcher/market-watcher.css
  src/components/market-watcher/market-watcher.html
  src/components/market-watcher/stoct-chart.directive.js
  src/components/network-monitor/network-monitor.html
  src/components/search/search.html
  src/components/top-accounts/top-accounts.html
  src/components/transactions/transactions.html
  src/directives/depth-chart.js
  src/index.ejs
  src/shared/peers/peers.html
  src/shared/transaction-item/transaction-item.html
  src/shared/transactions-list/transactions-list.html
  src/shared/votes/votes.html
Labels: pending review

#500 Peers mapper update - Solves #497
  lib/api/statistics.js
Labels: ready

#503 Fix block height on top bar - Closes #472
  lib/api/blocks.js
Labels: pending review

#478 Remove delegate proposal functionality - Closes #473
  api/delegates.js
  config.docker.js
  config.global.js
  config.js
  lib/api/delegates.js
  sockets/header.js
  src/assets/styles/common.css
  src/components/address/address.html
  src/components/delegate-monitor/delegate-monitor.component.js
  src/components/delegate-monitor/delegate-monitor.html
  src/components/delegate-monitor/delegate-monitor.service.js
  src/components/delegate/delegate.html
  src/components/header/header.directive.js
  src/components/header/header.service.js
  src/filters/index.js
  src/filters/proposal.js
  test/api/delegates.js
  test/config.test
Labels: in progress

#518 Geolocation data included in the Network Monitor socket response - Closes #517
  lib/api/statistics.js
Labels: :white_check_mark: ready

#515 Fix voters list on delegate page - Closes #502
  lib/api/accounts.js
  test/api/accounts.js
Labels: :eye: pending review

#527 Delegate data missing - Closes #526
  lib/api/delegates.js
  sockets/delegateMonitor.js
Labels: :white_check_mark: ready

#525 Mapping stability fix - Closes #523
  lib/api/accounts.js
  lib/api/blocks.js
  lib/api/delegates.js
  lib/api/statistics.js
Labels: :eye: pending review

#530 Check if delegate last block is present - Closes #529
  sockets/delegateMonitor.js
Labels: :eye: pending review

#533 Support for the betanet nethash
  src/filters/net-hash.js
Labels: :eye: pending review

#531 Fix delegate url on delegagte monitor page
  lib/api/delegates.js
Labels: :eye: pending review

#509 Add version number to HTML template - Closes #480
  src/index.ejs
  webpack.config.js
Labels: :eye: pending review

#519 Locked npm version in the Dockerfile - Closes #491
  Dockerfile
Labels: :eye: pending review

#541 Invalid reverse dns fix - Closes #540
  lib/api/statistics.js
Labels: :eye: pending review

#505 Get rid of config.docker.js file - Closes #504
  Dockerfile
  Jenkinsfile
  config.docker.js
  config.js
  test/config.test
Labels: :building_construction: in progress

#539 Transaction view: Added/deleted votes are visible - Closes #535
  lib/api/transactions.js
Labels: :white_check_mark: ready

#546 Fix latest votes list not showing username - Closes #544
  lib/api/delegates.js
Labels: :white_check_mark: ready

#548 Network Monitor: Incorrect best block amount - Closes #547
  lib/api/statistics.js
Labels: :eye: pending review

#551 Add test for voters - Closes #470
  test/api/accounts.js
Labels: :eye: pending review

#549 The Explorer checks node version before start - Closes #516
  app.js
Labels: :eye: pending review

#554 Fine tuning and improvements in UI - Closes #536
  src/assets/styles/common.css
  src/components/blocks/blocks.html
  src/components/header/header.css
  src/components/header/header.html
  src/components/home/home.html
  src/components/market-watcher/market-watcher.css
  src/components/network-monitor/network-monitor.html
  src/components/search/search.directive.js
  src/components/search/search.html
  src/components/top-accounts/top-accounts.html
  src/shared/transaction-item/transaction-item.html
  src/shared/transactions-list/transactions-list.html
Labels: :building_construction: in progress

#557 Latest Blocks list not showing username - Closes #555
  lib/api/blocks.js
Labels: :eye: pending review

#513 Order peers list based on version number - Closes #449
  src/components/network-monitor/network-monitor.service.js
  src/services/order-by.js
  src/shared/peers/peers.html
Labels: :eye: pending review

#553 Voters list not displaying known username - Closes #550
  Jenkinsfile
  app.js
  config.global.js
  config.js
  lib/api/accounts.js
  lib/api/delegates.js
  utils/knownAddresses.js
Labels: :eye: pending review

#570 Fix number of trades - Closes #569
  lib/api/candles.js
Labels: :eye: pending review

#566 Add abstraction layer for generic HTTP and Lisk Core requests - Closes #565
  api/handler.js
  config.js
  lib/api/accounts.js
  package.json
  utils/core.js
  utils/http.js
Labels: :white_check_mark: ready

#568 Network Monitor table sorting update - Closes #560
  src/components/delegate-monitor/delegate-monitor.html
  src/components/network-monitor/network-monitor.service.js
  src/services/order-by.js
  src/shared/peers/peers.html
Labels: :white_check_mark: ready

#574 Market Watcher stability fix - Closes #545
  lib/orders/abstract.js
  lib/orders/bittrex.js
  utils/exchange-api/index.js
Labels: :white_check_mark: ready

#576 Add no result state template to top accounts - Subtask #537
  src/assets/styles/common.css
  src/components/top-accounts/top-accounts.component.js
  src/components/top-accounts/top-accounts.html
  src/services/less-more.js
Labels: :white_check_mark: ready

#572 Merge 2.0 fixes - Closes #571
  Dockerfile
  Jenkinsfile
  config.docker.js
  config.js
  lib/api/candles.js
  lib/api/statistics.js
  lib/orders/abstract.js
  lib/orders/bittrex.js
  package.json
  src/components/delegate-monitor/delegate-monitor.html
  src/index.ejs
  utils/exchange-api/index.js
  webpack.config.js
Labels: :white_check_mark: ready

#580 Sorting issue fix - Closes #579
  src/shared/transactions-list/transactions-list.html
Labels: :white_check_mark: ready

#581 Broken search fix - Closes #578
  api/handler.js
Labels: :white_check_mark: ready

#575 Update e2e tests - Closes #507
  features/address.feature
  features/delegate.feature
  features/footer.feature
  features/home.feature
  features/menu.feature
  features/networkMonitor.feature
  features/topAccounts.feature
  test/known.test.json
Labels: :eye: pending review

#564 Replace old logo and icons with the new Lisk logo - Closes #524
  package.json
  src/assets/img/apple-touch-icon-114x114.png
  src/assets/img/apple-touch-icon-120x120.png
  src/assets/img/apple-touch-icon-144x144.png
  src/assets/img/apple-touch-icon-152x152.png
  src/assets/img/apple-touch-icon-57x57.png
  src/assets/img/apple-touch-icon-60x60.png
  src/assets/img/apple-touch-icon-72x72.png
  src/assets/img/apple-touch-icon-76x76.png
  src/assets/img/favicon-128.png
  src/assets/img/favicon-16x16.png
  src/assets/img/favicon-196x196.png
  src/assets/img/favicon-32x32.png
  src/assets/img/favicon-96x96.png
  src/assets/img/favicon.ico
  src/assets/img/favicons/android-chrome-192x192.png
  src/assets/img/favicons/android-chrome-512x512.png
  src/assets/img/favicons/apple-touch-icon.png
  src/assets/img/favicons/browserconfig.xml
  src/assets/img/favicons/favicon-16x16.png
  src/assets/img/favicons/favicon-32x32.png
  src/assets/img/favicons/favicon.ico
  src/assets/img/favicons/mstile-150x150.png
  src/assets/img/favicons/safari-pinned-tab.svg
  src/assets/img/mstile-144x144.png
  src/assets/img/mstile-150x150.png
  src/assets/img/mstile-310x150.png
  src/assets/img/mstile-310x310.png
  src/assets/img/mstile-70x70.png
  src/index.ejs
Labels: :eye: pending review

#595 Duplicated peers fix - Closes #594
  lib/api/statistics.js
  test/api/statistics.js
Labels: :eye: pending review
