Repository LiskHQ/lisk-explorer, pull requests merged in 2018-12, with the labels that each got.

#836 Search box auto capitalization - Closes #823
  src/components/search/search.html
Labels: :eye: pending review

#834 Webpack config for development mode - Closes #833
  webpack.config.js
Labels: :eye: pending review

#842 Configure cookie expiry date - Closes #841
  src/app/app.js
  src/components/cookies-banner/cookies-banner.directive.js
Labels: :white_check_mark: ready

#847 Explorer redesign - Closes #796 #813 #816 #820 #825
  lib/api/accounts.js
  src/assets/styles/common.css
  src/components/activity-graph/activity-graph.html
  src/components/address/address.component.js
  src/components/address/address.html
  src/components/blocks/block.html
  src/components/blocks/blocks.html
  src/components/bread-crumb/bread-crumb.css
  src/components/bread-crumb/bread-crumb.html
  src/components/currency-selector/currency-selector.html
  src/components/delegate-monitor/delegate-monitor.html
  src/components/delegate/delegate.html
  src/components/footer/footer.html
  src/components/header/header.html
  src/components/home/home.component.js
  src/components/home/home.html
  src/components/market-watcher/market-watcher.html
  src/components/navigation-dropdown/navigation-dropdown.html
  src/components/network-monitor/network-monitor.css
  src/components/network-monitor/network-monitor.html
  src/components/network-monitor/network-monitor.service.js
  src/components/rounding-selector/rounding-selector.html
  src/components/top-accounts/top-accounts.html
  src/components/transactions/transaction.html
  src/components/transactions/transactions.component.js
  src/components/transactions/transactions.html
  src/directives/account-href.js
  src/services/address-txs.js
  src/services/all-txs.js
  src/services/pagination.js
  src/shared/transactions-filter/transactions-filter.html
  src/shared/transactions-list/transactions-list.html
  src/shared/votes/votes.html
  test/api/accounts.js
Labels: :eye: pending review

#846 Fix routing - Closes #827
  src/app/app.js
  src/app/states.js
Labels: :eye: pending review

#840 Fontawesome Update - Closes #839
  package-lock.json
  package.json
  src/app/app.js
  src/assets/styles/common.css
  src/components/footer/footer.html
  src/index.ejs
Labels: :eye: pending review

#856 Adjust Spacing on big-info elements 2 - Closes #852
  src/assets/styles/common.css
  src/components/home/home.html
Labels: :eye: pending review

#853 Footer Icons Updates - Closes #848
  src/assets/styles/common.css
  src/components/footer/footer.html
Labels: :white_check_mark: ready

#857 Pagination logic update - #850
  src/components/transactions/transactions.component.js
  src/services/pagination.js
  src/shared/transactions-list/transactions-list.html
Labels: :white_check_mark: ready

#855 Currency picker fix - #849
  src/assets/styles/common.css
  src/components/bread-crumb/bread-crumb.html
  src/components/currency-selector/currency-selector.html
  src/components/rounding-selector/rounding-selector.directive.js
  src/components/rounding-selector/rounding-selector.html
Labels: :white_check_mark: ready

#861 UI update for Network Monitor page - #859
  src/assets/styles/common.css
  src/components/network-monitor/network-monitor.html
Labels: :white_check_mark: ready

#862 Modifiy the padding-bottom for h1 - Closes #859
  src/assets/styles/common.css
  src/assets/styles/tableMobile.css
Labels: :eye: pending review

#865 Align logo and nav bar to the container - Closes #859
  src/assets/styles/common.css
  src/components/header/header.css
Labels: :eye: pending review

#860 URL-based filters - Closes #814
  lib/api/transactions.js
  src/app/states.js
  src/assets/styles/common.css
  src/components/address/address.html
  src/components/transactions/transactions.component.js
  src/components/transactions/transactions.html
  src/services/pagination.js
  src/shared/transactions-filter/transactions-filter.directive.js
  src/shared/transactions-filter/transactions-filter.html
  src/shared/transactions-list/transactions-list.html
  utils/knownAddresses.js
Labels: :eye: pending review

#866 Home page redesign - Closes #859
  src/assets/styles/common.css
  src/components/home/home.component.js
  src/components/home/home.html
Labels: :building_construction: in progress

#863 Improve general UI of Delegate Monitor page - #859
  package-lock.json
  package.json
  src/assets/styles/common.css
  src/components/delegate-monitor/delegate-monitor.css
  src/components/delegate-monitor/delegate-monitor.html
Labels: :eye: pending review

#867 Add a page indicator to account page - Closes #858
  src/assets/styles/common.css
  src/components/blocks/blocks.html
  src/services/pagination.js
  src/shared/transactions-list/transactions-list.html
Labels: :eye: pending review

#871 Log levels update - Closes #870
  utils/candles.js
  utils/exchange-api/index.js
  utils/orders.js
Labels: :building_construction: in progress

#869 Fix grid of top section of Delegate Monitor - Closes #859
  src/assets/styles/common.css
  src/components/delegate-monitor/delegate-monitor.html
Labels: :eye: pending review

#872 Show only positive numbers for the transaction pagination - #859
  src/components/transactions/transactions.component.js
Labels: :eye: pending review
